### ISSUE TITLE
评论失败 错误代码：200

### ISSUE THREAD

**Issue by OxYancy** [cat3399/shoushuba#2]
评论失败
错误代码：200

**Comment by cat3399** [comment]
信息太少了，config.txt文件的第一行应该填搜书吧的url，比如现在是https://www.284djs.soushu2028.com/  第二行第三方分别填账号密码

**Comment by OxYancy** [comment]
能正常获取硬币  不能自动评论

**Comment by cat3399** [comment]
报错信息发下看看，我测试是没有问题的

**Comment by OxYancy** [comment]
保错信息就是这个

**Comment by cat3399** [comment]
把97行，print(pinlun.text)的注释取消掉，看看输出什么

**Comment by Ouyangchenxing** [comment]
出现错误，请重试！！！
用户信息页面获取成功:
失败
list index out of range
出现错误，请重试！！！
用户信息页面获取成功:
失败
list index out of range
出现错误，请重试！！！
用户信息页面获取成功:
我的一直这样循环

**Comment by cat3399** [comment]
登陆成功了吗

**Comment by cat3399** [comment]
> 出现错误，请重试!! 用户信息页面获取成功： 失败 list index out of range 出现错误，请重试!! 用户信息页面获取成功： 失败 list index out of range 出现错误，请重试!! 用户信息页面获取成功： 我的一直这样循环


登陆成功了吗

**Comment by Ouyangchenxing** [comment]
> 登陆成功了吗

不知道啊输出日志就一直循环这个

**Comment by cat3399** [comment]
> > 登陆成功了吗
> 
> 不知道啊输出日志就一直循环这个

没有输出登陆成功就是没有登陆成功，在config.txt文件第一行填入https://www.284djs.soushu2028.com/

**Comment by Ouyangchenxing** [comment]
> > > 登陆成功了吗
> > 
> > 
> > 不知道啊输出日志就一直循环这个
> 
> 没有输出登陆成功就是没有登陆成功，在config.txt文件第一行填入https://www.284djs.soushu2028.com/

填过了，就是这么填的啊

**Comment by cat3399** [comment]
> > > > 登陆成功了吗
> > > 
> > > 
> > > 不知道啊输出日志就一直循环这个
> > 
> > 
> > 没有输出登陆成功就是没有登陆成功，在config.txt文件第一行填入https://www.284djs.soushu2028.com/
> 
> 填过了，就是这么填的啊
config.txt应该是这样的

https://www.284djs.soushu2028.com/
username
password
就三行，不要有多余的空行

脚本正常的输出应该是这样的，
账号：XXXX 登录成功！！！
用户信息页面获取成功:
银币数量获取成功
当前银币数量: 174   
银币数量获取成功
当前银币数量: 175   
评论成功，此次评论的帖子tid为 XXXX ,评论的内容为 谢谢楼主分享，祝搜书吧越办越好！ ,等待60s后再次评论

报list index out of range是因为没有获取到要评论的帖子tid列表，有可能是因为没有登陆成功

**Comment by cat3399** [comment]
我应该知道为什么了，搜书吧有时候会禁止评论，应该是刚好碰上了，我刚刚尝试运行脚本也评论失败，提示<?xml version="1.0" encoding="gbk"?>
<root><![CDATA[站点功能性维护，目前当前版块禁止回帖，明日8点恢复<script type="text/javascript" reload="1">if(typeof errorhandle_register=='function') {errorhandle_register('站点功能性维护，目前当前版块禁止回帖，明日8点恢复', {});}</script>]]></root>

**Comment by Ouyangchenxing** [comment]
> > > > > 登陆成功了吗
> > > > 
> > > > 
> > > > 不知道啊输出日志就一直循环这个
> > > 
> > > 
> > > 没有输出登陆成功就是没有登陆成功，在config.txt文件第一行填入https://www.284djs.soushu2028.com/
> > 
> > 
> > 填过了，就是这么填的啊
> > config.txt应该是这样的
> 
> https://www.284djs.soushu2028.com/ username password 就三行，不要有多余的空行
> 
> 脚本正常的输出应该是这样的， 账号：XXXX 登录成功！！！ 用户信息页面获取成功: 银币数量获取成功 当前银币数量: 174   银币数量获取成功 当前银币数量: 175   评论成功，此次评论的帖子tid为 XXXX ,评论的内容为 谢谢楼主分享，祝搜书吧越办越好！ ,等待60s后再次评论
> 
> 报list index out of range是因为没有获取到要评论的帖子tid列表，有可能是因为没有登陆成功

我把用户名改成邮箱现在可以了，难道中文的用户名不行？

**Comment by cat3399** [comment]
> > > > > > 登陆成功了吗
> > > > > 
> > > > > 
> > > > > 不知道啊输出日志就一直循环这个
> > > > 
> > > > 
> > > > 没有输出登陆成功就是没有登陆成功，在config.txt文件第一行填入https://www.284djs.soushu2028.com/
> > > 
> > > 
> > > 填过了，就是这么填的啊
> > > config.txt应该是这样的
> > 
> > 
> > https://www.284djs.soushu2028.com/ username password 就三行，不要有多余的空行
> > 脚本正常的输出应该是这样的， 账号：XXXX 登录成功！！！ 用户信息页面获取成功: 银币数量获取成功 当前银币数量: 174   银币数量获取成功 当前银币数量: 175   评论成功，此次评论的帖子tid为 XXXX ,评论的内容为 谢谢楼主分享，祝搜书吧越办越好！ ,等待60s后再次评论
> > 报list index out of range是因为没有获取到要评论的帖子tid列表，有可能是因为没有登陆成功
> 
> 我把用户名改成邮箱现在可以了，难道中文的用户名不行？

很有可能，我没考虑过中文用户名的情况
