### ISSUE TITLE
评论在网站上看是乱码

### ISSUE THREAD

**Issue by chutney6** [cat3399/shoushuba#3]
如题，具体显示为
澶劅璋簡澶劅璋簡澶劅璋簡
鐪嬩簡LZ鐨勫笘瀛愶紝鎴戝彧鎯宠涓

脚本内显示是成功评论，没有乱码

**Comment by cat3399** [comment]
> 如题，具体显示为
> 澶劅璋簡澶劅璋簡澶劅璋簡
> 鐪嬩簡LZ鐨勫笘瀛愶紝鎴戝彧鎯宠涓
> 
> 脚本内显示是成功评论，没有乱码
> 
> 

还真是，我等会修一下

**Comment by chutney6** [comment]
> > 如题，具体显示为
> > 澶劅璋簡澶劅璋簡澶劅璋簡
> > 鐪嬩簡LZ鐨勫笘瀛愶紝鎴戝彧鎯宠涓
> > 脚本内显示是成功评论，没有乱码
> 
> 还真是，我等会修一下

感谢兄弟了，那天一开始还正常评论了几条，后面就全是乱码，全部都是显示评论成功。
不过有一次最后出现了一段错误代码但是我手快关窗口了，只记得大概有gbk这个词，恐怕是编码问题

**Comment by cat3399** [comment]
> > > 如题，具体显示为 澶劅璋簡澶劅璋簡澶劅璋簡 鐪嬩簡LZ鐨勫笘瀛愶紝鎴戝彧厯宠涓 脚本内显示是成功评论，没有乱码
> > 
> > 
> > 还真是，我等会修一下
> 
> 感谢兄弟了，那天一开始还正常评论了几条，后面就全是乱码，全部都是显示评论成功。 不过有一次最后出现了一段错误代码，但是我手快关窗口了，只记得大概有gbk这个词，恐怕是编码问题

确实是编码问题，网站用的gbk格式
![image](https://github.com/user-attachments/assets/0c90a47c-d7ee-4a56-9f3b-05316232d7e3)
。。。。。。。已经解决了，替换下脚本就行

**Comment by chutney6** [comment]
> > > > 如题，具体显示为 澶劅璋簡澶劅璋簡澶劅璋簡 鐪嬩簡LZ鐨勫笘瀛愶紝鎴戝彧厯宠涓 脚本内显示是成功评论，没有乱码
> > > 
> > > 
> > > 还真是，我等会修一下
> > 
> > 
> > 感谢兄弟了，那天一开始还正常评论了几条，后面就全是乱码，全部都是显示评论成功。 不过有一次最后出现了一段错误代码，但是我手快关窗口了，只记得大概有gbk这个词，恐怕是编码问题
> 
> 确实是编码问题，网站用的gbk格式 ![image](https://private-user-images.githubusercontent.com/127954618/353547582-0c90a47c-d7ee-4a56-9f3b-05316232d7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzODc1MTksIm5iZiI6MTcyMjM4NzIxOSwicGF0aCI6Ii8xMjc5NTQ2MTgvMzUzNTQ3NTgyLTBjOTBhNDdjLWQ3ZWUtNGE1Ni05ZjNiLTA1MzE2MjMyZDdlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwMDUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDFhZGMxN2NiYWNkY2IwY2Q5MWMxMzU1MGJjM2EwYmM2MWFiZGNiN2RiOGRlZjEzODIxZGE2YWUzMzEzMDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jyb_kIWw_Rh9vxQUrAgmCisxhJgMJIVZAt1CQNi-13U) 。。。。。。。已经解决了，替换下脚本就行

确实可以了，辛苦兄弟
